cluster.name: "docker-cluster"
network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1
#discovery.type: single-node
#bootstrap.memory_lock: true
xpack.license.self_generated.type: basic
xpack.security.enabled: false
# Search Guard

searchguard.enterprise_modules_enabled: true

searchguard.ssl.transport.keystore_filepath: sg/node-0-keystore.jks
searchguard.ssl.transport.truststore_filepath: sg/truststore.jks
searchguard.ssl.transport.enforce_hostname_verification: false

searchguard.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,l=tEst,C=De

searchguard.restapi.roles_enabled:
  - SGS_ALL_ACCESS

#basic_internal_auth_domain:
#  enabled: true
#  order: 0
#  http_authenticator:
#    type: basic
#    challenge: false
#  authentication_backend:
#    type: internal
#openid_auth_domain:
#  enabled: true
#  order: 1
#  http_authenticator:
#    type: openid
#    challenge: false
#    config:
#      subject_key: preferred_username
#      roles_key: roles
#      openid_connect_url: http://localhost:8080/auth/realms/TestRealm/.well-known/openid-configuration
#  authentication_backend:
#    type: noop