version: '2.0'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.allow-origin=*
      - ELASTIC_PASSWORD=$ELK_PASSWORD
    #  PFrYZ95pn4JRCuz483v1
    ulimits:
      memlock:
        soft: -1
        hard: -1

    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/storage:/usr/share/elasticsearch/data:rw

    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: $ELK_PASSWORD
      
    volumes:
      - ./kibana/config:/usr/share/kibana/config
    networks:
      - elastic
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - ES_USER=elastic
      - ES_PASSWORD=$ELK_PASSWORD
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
    ports:
      - "5000:5000"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  curator:
    build:
      context: extensions/curator/
    init: true
    volumes:
      - type: bind
        source: ./extensions/curator/config/curator.yml
        target: /usr/share/curator/config/curator.yml
        read_only: true
      - type: bind
        source: ./extensions/curator/config/delete_log_files_curator.yml
        target: /usr/share/curator/config/delete_log_files_curator.yml
        read_only: true
    depends_on:
      - elasticsearch
    networks:
      - elastic
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - './nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './nginx/public:/usr/share/nginx/html:ro'
      - './nginx/etc/.htpasswd.user:/etc/nginx/.htpasswd.user:ro'
    links:
      - elasticsearch
      - kibana
    depends_on:
      - elasticsearch
      - kibana
    ports:
      - '80:80'
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
