# Curator configuration
# https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html

client:
  hosts:
    - elasticsearch
  port: 9200
  http_auth: elastic:izy0dx3EmAPTr8hnFrC6

logging:
  loglevel: INFO
#  logfile: ./logs/log.log
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']