
# Description:
# Default Kibana configuration from kibana-docker.

server.name: kibana
server.host: "0"
elasticsearch.hosts: https://elasticsearch:9200
elasticsearch.ssl.verificationMode: none
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
elasticsearch.requestHeadersWhitelist: ["Authorization", "security_tenant"]
# Enable OpenID authentication
opendistro_security.auth.type: "openid"
#server.ssl.enabled: false

# The IdP metadata endpoint
opendistro_security.openid.connect_url: "http://authServer:8080/auth/realms/TestRealm/.well-known/openid-configuration"

# The ID of the OpenID Connect client in your IdP
opendistro_security.openid.client_id: kibana-sso
opendistro_security.openid.base_redirect_url: "http://authServer:5601"
# The client secret of the OpenID Connect client
opendistro_security.openid.client_secret: "dd622848-f8be-4290-806e-a5a186416433"

# Use HTTPS instead of HTTP
#elasticsearch.url: "https://elasticsearch:9200"

# Configure the Kibana internal server use

# Disable SSL verification when using self-signed demo certificates

# Whitelist basic headers and multi-tenancy header